[2018-09-20 23:40:03,381][INFO][BrowserEngine][get_driver]:Get current driver, ID: 506032968, Driver: None
[2018-09-20 23:59:42,644][ERROR][BrowserEngine][launch_local_browser]:Fail to launch browser
Traceback (most recent call last):
  File "D:/Program Files (x86)/JetBrains/MyAutoTestFrameWork\Src\BrowserEngine.py", line 25, in launch_local_browser
    self.driver = webdriver.Firefox(executable_path=FIREFOX_DRIVER_DIR)
  File "D:\Python27\lib\site-packages\selenium-3.9.0-py2.7.egg\selenium\webdriver\firefox\webdriver.py", line 162, in __init__
    keep_alive=True)
  File "D:\Python27\lib\site-packages\selenium-3.9.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\selenium-3.9.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\selenium-3.9.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\selenium-3.9.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\selenium-3.9.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 490, in _request
    resp = self._conn.getresponse()
  File "D:\Python27\lib\httplib.py", line 1045, in getresponse
    response.begin()
  File "D:\Python27\lib\httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "D:\Python27\lib\httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "D:\Python27\lib\socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 10054] 
[2018-09-20 23:59:44,283][INFO][BrowserEngine][quit_browser]:Quit browser and release current driver
