[2018-09-17 21:36:58,901][ERROR][Decorator][wrapper]:[UnwantedException]:
Traceback (most recent call last):
  File "D:\Program Files (x86)\JetBrains\MyAutoTestFrameWork\Utils\Decorator.py", line 94, in wrapper
    result = func(self, *args, **kwargs)
  File "D:\Program Files (x86)\JetBrains\MyAutoTestFrameWork\Src\Wait.py", line 102, in element_visible
    ec.visibility_of_element_located(locator), 'Wait element {0} visible'.format(locator)
  File "D:\Python27\lib\site-packages\selenium-3.9.0-py2.7.egg\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "D:\Python27\lib\site-packages\selenium-3.9.0-py2.7.egg\selenium\webdriver\support\expected_conditions.py", line 127, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "D:\Python27\lib\site-packages\selenium-3.9.0-py2.7.egg\selenium\webdriver\support\expected_conditions.py", line 397, in _find_element
    return driver.find_element(*by)
AttributeError: 'NoneType' object has no attribute 'find_element'
